//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ID xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; descr=&quot;kjv&quot; alphabet=&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz&quot;&gt;
        ///  &lt;BOOK bnumber=&quot;1&quot; bshort=&quot;ge;gen;gn;genesis&quot;&gt;Genesis&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;2&quot; bshort=&quot;ex;exo;exod;exodus&quot;&gt;Exodus&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;3&quot; bshort=&quot;lev;le;lv;levit;leviticus&quot;&gt;Leviticus&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;4&quot; bshort=&quot;nu;num;nm;numb;numbers&quot;&gt;Numbers&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;5&quot; bshort=&quot;de;deut;deu;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BibleBooskInfo_kjv {
            get {
                return ResourceManager.GetString("BibleBooskInfo_kjv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ID descr=&quot;rst&quot; alphabet=&quot;АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя&quot;&gt;
        ///  &lt;BOOK bnumber=&quot;1&quot; bshort=&quot;быт;бт;бытие&quot;&gt;Бытие&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;2&quot; bshort=&quot;исх;исход&quot;&gt;Исход&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;3&quot; bshort=&quot;лев;лв;левит&quot;&gt;Левит&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;4&quot; bshort=&quot;чис;чс;числ;числа&quot;&gt;Числа&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;5&quot; bshort=&quot;втор;вт;втрзк;второзаконие&quot;&gt;Второзаконие&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;6&quot; bshort=&quot;нав;иисус;навин&quot;&gt;Иисус Навин&lt;/BOOK&gt;
        ///  &lt;BOOK bnumber=&quot;7&quot; bshor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BibleBooskInfo_rst {
            get {
                return ResourceManager.GetString("BibleBooskInfo_rst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;BibleTranslationDifferences xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; PartVersesAlphabet=&quot;абвгд&quot;&gt;
        ///  &lt;BookDifferences BookIndex=&quot;3&quot;&gt;
        ///    &lt;Difference BaseVerses=&quot;14:55-56&quot; ParallelVerses=&quot;14:55&quot; /&gt;
        ///    &lt;Difference BaseVerses=&quot;14:57&quot; ParallelVerses=&quot;14:56&quot; /&gt;
        ///  &lt;/BookDifferences&gt;
        ///  &lt;BookDifferences BookIndex=&quot;4&quot;&gt;
        ///    &lt;Difference BaseVerses=&quot;12:16&quot; ParallelVerses=&quot;13:1&quot; /&gt;
        ///    &lt;Difference BaseVerses=&quot;13:1-33&quot; ParallelVerses= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rst {
            get {
                return ResourceManager.GetString("rst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BibleTranslationDifferences xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; PartVersesAlphabet=&quot;абвгд&quot;&gt;
        ///  &lt;BookDifferences BookIndex=&quot;3&quot;&gt;
        ///    &lt;Difference BaseVerses=&quot;14:55-56&quot; ParallelVerses=&quot;14:55&quot; /&gt;
        ///    &lt;Difference BaseVerses=&quot;14:57&quot; ParallelVerses=&quot;14:56&quot; /&gt;
        ///  &lt;/BookDifferences&gt;
        ///  &lt;BookDifferences BookIndex=&quot;4&quot;&gt;
        ///    &lt;Difference BaseVerses=&quot;12:16&quot; ParallelVerses=&quot;13:1&quot; /&gt;
        ///    &lt;Difference BaseVerses=&quot;13:1-3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rst77 {
            get {
                return ResourceManager.GetString("rst77", resourceCulture);
            }
        }
    }
}
